[package]
name = "assigment5"
version = "0.1.0"
authors = ["shoaib muneer <shoaib76muneer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
